name: Auto code promotion

on:
  schedule:
    - cron: '* * * * *' # Runs at the 1st minute of every hour
  
  workflow_dispatch: {} # Corrected: Removed the 's'

jobs:
  automations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install runner and execute
        run: |
          npm install -g tsx
          npx tsx .github/scripts/cron-job.ts