name: Issue Notifier

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        env:
          # Map inputs to env variables to avoid syntax errors
          ISSUE_TITLE: ${{ inputs.title }}
          ISSUE_MESSAGE: ${{ inputs.message }}
        with:
          script: |
            const { ISSUE_TITLE, ISSUE_MESSAGE } = process.env;
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: ISSUE_TITLE,
              body: ISSUE_MESSAGE
            });