name: Issue Notifier
on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      message:
        required: true
        type: string

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Create GitHub Issue
        uses: actions/github-script@v7
        with:
          script: | 
            github.rest.issue.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "{{ input.title }}"
              body: "{{ input.message }}"
            })